# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0006_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pinax_stripe.Customer'),
        ),
    ]
