# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0007_auto_20170125_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pinax_stripe.Customer'),
        ),
    ]
