# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0008_auto_20170130_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pinax_stripe.Customer'),
        ),
    ]
